n = int(input('Digite um número para ver sua tabuada: '))
print('-' * 15)
print(f'{n} X {1:3} = {n*1}')
print(f'{n} X {2:3} = {n*2}')
print(f'{n} X {3:3} = {n*3}')
print(f'{n} X {4:3} = {n*4}')
print(f'{n} X {5:3} = {n*5}')
print(f'{n} X {6:3} = {n*6}')
print(f'{n} X {7:3} = {n*7}')
print(f'{n} X {8:3} = {n*8}')
print(f'{n} X {9:3} = {n*9}')
print(f'{n} X {10} = {n*10}')
print('-' * 15)